apiVersion: v1
kind: LimitRange
metadata:
  labels:
    author: gpbu5601
  name: core-resource-limits
spec:
  limits:
  - type: Pod
    max:
      cpu: "4"
      memory: 6Gi
    min:
      cpu: 50m
      memory: 6Mi
  - type: Container
    default:
      cpu: "2"
      memory: 4Gi
    defaultRequest:
      cpu: 500m
      memory: 512Mi
    max:
      cpu: "4"
      memory: 4Gi
    maxLimitRequestRatio:
      cpu: "40"
    min:
      cpu: 50m
      memory: 6Mi
    type: Container