apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv-1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/okd4/sysvol/elasticsearch-1
    server: nfs.dev.example.ru
    readOnly: false
  storageClass: nfs
