apiVersion: v1
kind: Secret
metadata:
  labels:
    app: ldap-sync
  name: ldap-sync
  namespace: ldap-sync
type: Opaque
data:
  BIND_DN: Y249b3BlbnNoaWZ0LG91PURFVixkYz1kZXYsZGM9ZXhhbXBsZSxkYz1ydQo
  BIND_PASSWORD: ZnVjayB5b3UsIHlvdSBzbmVha3kgYmFzdGFydAo=
