kind: LDAPSyncConfig
apiVersion: v1
url: ldap://ldap.dev.example.ru:389
bindDN: cn=openshift,ou=DEV,dc=dev,dc=example,dc=ru
bindPassword: 'passw0rd'
insecure: true
groupUIDNameMapping:
  "cn=OpenShift-Cluster-Admins,ou=DEV,dc=dev,dc=example,dc=ru": OpenShift-Cluster-Admins
  "cn=OpenShift-Cluster-Viewers,ou=DEV,dc=dev,dc=example,dc=ru": OpenShift-Cluster-Viewers
activeDirectory:
  usersQuery:
    baseDN: "ou=DEV,dc=dev,dc=example,dc=ru"
    scope: sub
    derefAliases: never
    pageSize: 0
    filter: (&(objectClass=inetOrgPerson)(isMemberOf=cn=OpenShiftUsers,ou=DEV,dc=dev,dc=example,dc=ru)(!(isMemberOf=cn=LockedUsers,ou=DEV,dc=dev,dc=example,dc=ru)))
  userNameAttributes: [ cn ]
  groupMembershipAttributes: [ isMemberOf ]