apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: localvol-prom
  namespace: "openshift-local-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - okd4-i0
          - okd4-i1
          - okd4-i2
  storageClassDevices:
    - storageClassName: localvol-sc-prom
      volumeMode: Filesystem
      devicePaths:
        - /dev/mapper/vg_locvol-lv_prom
