apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pvX
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /srv/nfs/okd4/usrvol/pvX
    server: nfs.dev.example.ru
    readOnly: false