apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/okd4/sysvol/registry
    server: nfs.dev.example.ru
    readOnly: false
  claimRef:
    name: image-registry-storage
    namespace: openshift-image-registry
  storageClass: nfs
