apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: teamcity-rolebinding
  namespace: tc-okd4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: teamcity-role
subjects:
- kind: ServiceAccount
  name: teamcity
  namespace: tc-okd4
